// LOGIN
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

//LOGOUT
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';


//GETREQUEST   
export const GET_REQUEST_PENDING='GET_REQUEST_PENDING';
export const GET_REQUEST_FULFILLED='GET_REQUEST_FULFILLED';
export const GET_REQUEST_REJECTED= 'GET_REQUEST_REJECTED';


//REPORTS
export const GET_REPORTS_PENDING='GET_REPORTS_PENDING';
export const GET_REPORTS_FULFILLED='GET_REPORTS_FULFILLED';
export const GET_REPORTS_REJECTED='GET_REPORTS_REJECTED';

//FILE_UPLOAD

export const FILE_UPLOAD_PENDING='FILE_UPLOAD_PENDING';
export const FILE_UPLOAD_FULFILLED='FILE_UPLOAD_FULFILLED';
export const FILE_UPLOAD_REJECTED='FILE_UPLOAD_REJECTED';


//FILE_DOWNLOAD
export const FILE_DOWNLOAD_PENDING='FILE_DOWNLOAD_PENDING';
export const FILE_DOWNLOAD_FULFILLED='FILE_DOWNLOAD_FULFILLED';
export const FILE_DOWNLOAD_REJECTED='FILE_DOWNLOAD_REJECTED';


//CREATEREQUEST
export const SET_REPORT_ID_PENDING = 'SET_REPORT_ID_PENDING';
export const SET_REPORT_ID_FULFILLED = 'SET_REPORT_ID_FULFILLED';
export const SET_REPORT_INPUT_PENDING = 'SET_REPORT_INPUT_PENDING';
export const SET_REPORT_INPUT_FULFILLED = 'SET_REPORT_INPUT_FULFILLED';
export const SET_REPORT_OUTPUT_PENDING = 'SET_REPORT_OUTPUT_PENDING';
export const SET_REPORT_OUTPUT_FULFILLED = 'SET_REPORT_OUTPUT_FULFILLED';
export const CREATE_REQUEST_PENDING='CREATE_REQUEST_PENDING';
export const CREATE_REQUEST_FULFILLED='CREATE_REQUEST_FULFILLED';
export const CREATE_REQUEST_REJECTED='CREATE_REQUEST_REJECTED';


//ADHOC INPUTS
export const GET_ADHOC_REPORT_INPUT_REJECTED='GET_ADHOC_REPORT_INPUT_REJECTED';
export const GET_ADHOC_REPORT_INPUT_FULFILLED='GET_ADHOC_REPORT_INPUT_FULFILLED';
export const GET_ADHOC_REPORT_INPUT_PENDING='GET_ADHOC_REPORT_INPUT_PENDING';
export const SET_ADHOC_REPORT_INPUT_REJECTED='SET_ADHOC_REPORT_INPUT_REJECTED';
export const SET_ADHOC_REPORT_INPUT_FULFILLED='SET_REPORT_INPUT_FULFILLED';
export const SET_ADDHOC_REPROT_INPUT_PENDING='SET_REPORT_INPUT_PENDING';

//ADHOC OUTPUTS
export const GET_ADHOC_REPORT_OUTPUT_REJECTED='GET_ADHOC_REPORT_OUTPUT_REJECTED';
export const GET_ADHOC_REPORT_OUTPUT_FULFILLED='GET_ADHOC_REPORT_OUTPUT_FULFILLED';
export const GET_ADHOC_REPORT_OUTPUT_PENDING='GET_ADHOC_REPORT_OUTPUT_PENDING';
export const SET_ADHOC_REPORT_OUTPUT_PENDING='SET_ADHOC_REPORT_OUTPUT_PENDING';
export const SET_ADHOC_REPORT_OUTPUT_FULFILLED='SET_ADHOC_REPORT_OUTPUT_FULFILLED';
export const SET_ADDHOC_REPROT_INPUT_REJECTED='SET_ADHOC_REPORT_OUTPUT_REJECTED';   

//SCHEDULED REPORT
export const GET_SCHEDULED_REPORT_REJECTED='GET_SCHEDULED_REPORT_REJECTED';
export const GET_SCHEDULED_REPORT_FULFILLED='GET_SCHEDULED_REPORT_FULFILLED';
export const GET_SCHEDULED_REPORT_PENDING='GET_SCHEDULED_REPORT_PENDING';

